stages:
    - Build
    - Security_Scan
    - Deploy_Run
    - Dynamic_Analysis

Compile Application:
    image: maven:3.6.0-jdk-8
    stage: Build
    script:
      - mvn clean package
    artifacts:
      name: verademo_julian_10_build
      paths:
        - target/
      expire_in: 5 week
    cache:
      paths:
        - target/
        - .m2/repository

Build Docker Image:
    image: docker:19.03.8-dind 
    stage: Build
    services:
        - docker:19.03.8-dind
    before_script:
        - docker info
    script:
        - docker pull juliantotzek/verademo1-tomcat


Software Composition Analysis App 3rd party:
    image: maven:3.6.0-jdk-8
    stage: Security_Scan
    script:
        - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan . --update-advisor  2>&1 | tee sca_output.txt
    artifacts:
        paths:
            - sca_output.txt
        when: always
        name: "veracode-SCA-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: false

Software Composition Analysis Docker 3rd party:
    image: juliantotzek/dockercli
    stage: Security_Scan
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375
    before_script:
        - docker pull juliantotzek/verademo1-tomcat
    
    script:
        - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --image juliantotzek/verademo1-tomcat 2>&1 | tee sca_docker_output.txt
    artifacts:
        paths:
            - sca_docker_output.txt
        when: always
        name: "veracode-SCA-DOCKER-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: false

Pipeline Scan Staic Analysis:
    image: veracode/pipeline-scan:latest
    stage: Security_Scan
    only:
        - development
    script:
        - java -jar /opt/veracode/pipeline-scan.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} --file target/verademo.war --issue_details true --gl_issue_generation true -jf results.json 2>&1 | tee pipeline_scan_text_output.txt
    artifacts:
        paths:
            - results.json
            - pipeline_scan_text_output.txt
        when: always
        name: "veracode-pipeline-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: false
    
Sandbox Scan Static Analysis:
    image: veracode/api-wrapper-java
    stage: Security_Scan
    only:
        - release
    script:
        - java -jar /opt/veracode/api-wrapper.jar -vid ${TEAM_ANALYSISCENTER_ID} -vkey ${TEAM_ANALYSISCENTER_KEY}
          -action UploadAndScan -appname "Verademo" -createprofile true -autoscan true -sandboxname "gitlab-release" -createsandbox true
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" 2>&1 | tee sandbox_scan_output.txt
    artifacts:
        paths:
            - sandbox_scan_output.txt
        when: always
        name: "veracode-SANDBOX-SCAN-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    allow_failure: true
    
Policy Scan Static Analysis:
    image: veracode/api-wrapper-java
    stage: Security_Scan
    only:
        - schedules
        - master
    script:
        - java -jar /opt/veracode/api-wrapper.jar -vid ${TEAM_ANALYSISCENTER_ID} -vkey ${TEAM_ANALYSISCENTER_KEY}
          -action UploadAndScan -appname "Verademo" -createprofile false -autoscan true
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" 
          -scantimeout 15 2>&1 | tee policy_scan_output.txt
    artifacts:
        paths:
            - policy_scan_output.txt
        when: always
        name: "veracode-POLICY-SCAN-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

Docker Start:
    image: docker:19.03.8-dind 
    stage: Deploy_Run
    only:
        - development
        - release
        - master
    services:
         - docker:19.03.8-dind
    before_script:
            - docker info
    script:
        - docker run juliantotzek/verademo1-tomcat

Dynamic Analysis:
    image: veracode/api-signing
    stage: Dynamic_Analysis
    only:
        - development
        - release
        - master
    before_script:
        - export VERACODE_API_KEY_ID=${VERACODE_API_ID}
          export VERACODE_API_KEY_SECRET=${VERACODE_API_KEY}
    script:
        - http --auth-type veracode_hmac PUT https://api.veracode.com/was/configservice/v1/scan_occurrences/c09b91693bc1a95f82065f8f58f0d3d6?action=RESUBMIT
